!BINARY TO DECIMAL CONVERTER
PROGRAM BIN_TO_DEC
 IMPLICIT NONE
 INTEGER::I=0,J,BIN,DEC=0,DIG
 PRINT*,"ENTER A BINARY NUMBER FOR  CONVERTING"
  READ*,BIN
  DO 
   IF(BIN == 0)THEN
    EXIT
   ELSE
    DIG=MOD(BIN,10)
    DEC= DEC+DIG*(2**I)
    I=I+1
    BIN= BIN/10
   ENDIF
  END DO
 PRINT*,"DECIMAL EQUIVALENT NO=",DEC
END PROGRAM BIN_TO_DEC

